### ISSUE TITLE
The form has reached its maximum number of responses

### ISSUE THREAD

**Issue by Lancycool** [XinyiYing/RGBT-Tiny#13]
Google form has closed, and Microsoft form has reached its maximum number of responses when submitting the info

**Comment by XinyiYing** [comment]
We have fixed this problem, and you can access the dataset in Google form

**Comment by Lancycool** [comment]
> We have fixed this problem, and you can access the dataset in Google form

Sorry to bother u again. Did u update the url of Google form? I still can't open the Google form right now, and Microsoft form has reached its maximum number of responses

**Comment by XinyiYing** [comment]
We have checked this problem, please try again

**Comment by MaximClouser** [comment]
@XinyiYing could you please update the Google form again?
